"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['window.py']
APP_NAME = "Google Search Console Extractor"
DATA_FILES = ['background.png','button_1.png','entry_1.png','entry_2.png','entry_3.png','entry_4.png','entry_5.png']
OPTIONS = {
    'iconfile': 'logo.icns',
    'packages': ['pandas'],
    'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Haal eenvoudig data uit de Google Search Console API!",
        'CFBundleIdentifier': "com.thijsvanhal.osx.google_search_console_extractor",
        'CFBundleVersion': "1.3.1",
        'CFBundleShortVersionString': "1.0.0",
        'NSHumanReadableCopyright': u"Copyright © 2022, Thijs van Hal, All Rights Reserved"
	}
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
